"""PDF Report Generator"""
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import markdown2
from datetime import datetime
import os

class PDFReportGenerator:
    """Generate professional PDF reports from markdown"""
    
    def __init__(self, output_dir="/home/rpas/research_reports/pdfs"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        
    def markdown_to_pdf(self, markdown_content: str, title: str, agent_name: str, metadata: dict = None) -> str:
        """Convert markdown research report to PDF"""
        
        # Generate filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c if c.isalnum() or c in (' ', '_') else '_' for c in title)[:50]
        filename = f"{agent_name.replace(' ', '_')}_{safe_title}_{timestamp}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        # Create PDF document
        doc = SimpleDocTemplate(
            filepath,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        # Container for PDF elements
        story = []
        
        # Define styles
        styles = getSampleStyleSheet()
        
        # Title style
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor='#2C3E50',
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        # Subtitle style
        subtitle_style = ParagraphStyle(
            'CustomSubtitle',
            parent=styles['Normal'],
            fontSize=12,
            textColor='#7F8C8D',
            spaceAfter=12,
            alignment=TA_CENTER
        )
        
        # Heading style
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor='#34495E',
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        )
        
        # Body style
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=11,
            textColor='#2C3E50',
            alignment=TA_JUSTIFY,
            spaceAfter=12,
            leading=14
        )
        
        # Add title page
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 0.3*inch))
        story.append(Paragraph(f"Generated by: {agent_name}", subtitle_style))
        story.append(Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}", subtitle_style))
        
        if metadata:
            if metadata.get('model'):
                story.append(Paragraph(f"AI Model: {metadata['model']}", subtitle_style))
        
        story.append(PageBreak())
        
        # Convert markdown to HTML
        html_content = markdown2.markdown(markdown_content, extras=['fenced-code-blocks', 'tables'])
        
        # Parse markdown and add to PDF
        lines = markdown_content.split('\n')
        in_code_block = False
        current_list_items = []

        for i, line in enumerate(lines):
            stripped = line.strip()

            # Handle code blocks
            if stripped.startswith('```'):
                in_code_block = not in_code_block
                continue

            if in_code_block:
                # Code block content - skip for now (could add monospace styling)
                continue

            if not stripped:
                # Flush any pending list items
                if current_list_items:
                    for item in current_list_items:
                        story.append(Paragraph(f"• {item}", body_style))
                    current_list_items = []
                story.append(Spacer(1, 0.1*inch))
                continue

            # Handle headings
            if stripped.startswith('# '):
                if current_list_items:
                    for item in current_list_items:
                        story.append(Paragraph(f"• {item}", body_style))
                    current_list_items = []
                story.append(Spacer(1, 0.2*inch))
                story.append(Paragraph(self._escape_html(stripped[2:]), title_style))
            elif stripped.startswith('## '):
                if current_list_items:
                    for item in current_list_items:
                        story.append(Paragraph(f"• {item}", body_style))
                    current_list_items = []
                story.append(Spacer(1, 0.15*inch))
                story.append(Paragraph(self._escape_html(stripped[3:]), heading_style))
            elif stripped.startswith('### '):
                if current_list_items:
                    for item in current_list_items:
                        story.append(Paragraph(f"• {item}", body_style))
                    current_list_items = []
                story.append(Paragraph(self._escape_html(stripped[4:]), styles['Heading3']))
            elif stripped.startswith('- ') or stripped.startswith('* '):
                # Collect bullet points
                current_list_items.append(self._escape_html(stripped[2:]))
            elif stripped.startswith('**') and stripped.endswith('**') and len(stripped) > 4:
                # Bold standalone text
                if current_list_items:
                    for item in current_list_items:
                        story.append(Paragraph(f"• {item}", body_style))
                    current_list_items = []
                text = stripped[2:-2]
                story.append(Paragraph(f"<b>{self._escape_html(text)}</b>", body_style))
            else:
                # Regular paragraph - handle inline markdown
                if current_list_items:
                    for item in current_list_items:
                        story.append(Paragraph(f"• {item}", body_style))
                    current_list_items = []

                # Process inline formatting
                formatted_text = self._process_inline_markdown(stripped)
                story.append(Paragraph(formatted_text, body_style))

        # Flush any remaining list items
        if current_list_items:
            for item in current_list_items:
                story.append(Paragraph(f"• {item}", body_style))

        # Build PDF
        doc.build(story)

        return filepath

    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters"""
        return (text
                .replace('&', '&amp;')
                .replace('<', '&lt;')
                .replace('>', '&gt;'))

    def _process_inline_markdown(self, text: str) -> str:
        """Process inline markdown formatting (bold, italic, code)"""
        import re

        # Escape HTML first
        text = self._escape_html(text)

        # Bold: **text** or __text__
        text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
        text = re.sub(r'__(.+?)__', r'<b>\1</b>', text)

        # Italic: *text* or _text_
        text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
        text = re.sub(r'_(.+?)_', r'<i>\1</i>', text)

        # Inline code: `text`
        text = re.sub(r'`(.+?)`', r'<font name="Courier">\1</font>', text)

        return text

# Singleton instance
pdf_generator = PDFReportGenerator()
